# Generated by Django 5.0.6 on 2025-08-26 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "bookingid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=40)),
                ("paymentdetails", models.CharField(max_length=20)),
                ("totalamount", models.IntegerField()),
                ("bookingdate", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "bookingid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("servicename", models.CharField(max_length=25)),
                ("typeofcloth", models.CharField(max_length=40)),
                ("nopieces", models.IntegerField()),
                ("price", models.IntegerField()),
                ("username", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookingid", models.CharField(max_length=8)),
                ("username", models.CharField(max_length=40)),
                ("rating", models.IntegerField()),
                ("message", models.CharField(max_length=220)),
            ],
        ),
    ]
