# Generated by Django 5.0.6 on 2025-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cartitems",
            field=models.ManyToManyField(blank=True, to="customer.cart"),
        ),
    ]
