# Generated by Django 5.0.6 on 2024-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="addbranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branchname", models.CharField(max_length=25)),
                ("branchId", models.IntegerField()),
                ("Branchadd", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="addservice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicename", models.CharField(max_length=25)),
                ("typeofcloth", models.CharField(max_length=40)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="adminprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=25)),
                ("EmailId", models.EmailField(max_length=254)),
                ("PhoneNumber", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="clothtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typeofcloth", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=25)),
                ("EmailId", models.EmailField(max_length=254)),
                ("PhoneNumber", models.IntegerField()),
                ("Message", models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="userregistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=25)),
                ("username", models.CharField(max_length=40)),
                ("EmailId", models.EmailField(max_length=254)),
                ("PhoneNumber", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("userid", models.IntegerField()),
            ],
        ),
    ]
