# Generated by Django 5.0.6 on 2024-08-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_servicename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addservice",
            name="servicename",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.servicename",
            ),
        ),
        migrations.AlterField(
            model_name="addservice",
            name="typeofcloth",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.clothtype",
            ),
        ),
    ]
