# Generated by Django 5.0.6 on 2024-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_addservice_servicename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregistration",
            name="userid",
            field=models.CharField(max_length=10),
        ),
    ]
